cjDzfESt: Fixed the version of composer as 2.0 in php dockerfile, updated composer dependencies, resolved warnings while docker continer build and composer install
AVE-Systems/sonata-test-utils pull request #15
Opened 2021-01-19 06:45 UTC by pronata

https://trello.com/c/cjDzfESt

2021-01-19 06:46 UTC, pronata commented
![](https://github.trello.services/images/mini-trello-icon.png) [SonataTestUtils: Зафиксировать версии пакетов во всех Dockerfile-файлах](https://trello.com/c/cjDzfESt/1861-sonatatestutils-%D0%B7%D0%B0%D1%84%D0%B8%D0%BA%D1%81%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2-%D0%B2%D0%BE-%D0%B2%D1%81%D0%B5%D1%85-dockerfile-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0%D1%85)

2021-01-19 14:21 UTC, ArtemBurykin requested changes
Также, для библиотек обычно удаляют composer.lock из репа..

2021-01-19 14:21 UTC, ArtemBurykin commented on docker/php/Dockerfile
> +COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer
Хочу отметить, что композер два - довольно новая тема, и у большинства в проекте может стоять композер 1. Хоть это и не противоречит в большинстве случаев, тестируя библиотеку только под композером 2 мы, потенциально, добавляем шанс, что те у кого композер 1 могут встретить баг (скорее конфликт библиотек). Если тестировать только в одном контейнере - то я бы выбрал php 7.2 - composer 1 (как наиболее вероятная поставка для симфони на текущий момент). А так, потенциально, тестировать нужно в разных контейнерах..

2021-01-20 03:53 UTC, andomiell commented on docker/php/Dockerfile
> +RUN apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
А это интересно, для чего?

2021-01-20 03:54 UTC, andomiell approved these changes

2021-01-20 06:32 UTC, pronata commented on docker/php/Dockerfile
> +RUN apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
Для подчищения дискового пространства за установщиком. Когда делаем apt-get update, то список с файлами-установщиками опять возобновляется в /var/lib/apt/lists, а apt-get autoremove так понимаю удаляет промежуточные пакеты, которые нужны были для установки основных.

2021-01-20 06:33 UTC, pronata commented on docker/php/Dockerfile
> +COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer
Т.е. лучше нам пока использовать coposer 1, пока не обновим php в проекте?

2021-01-20 11:59 UTC, ArtemBurykin commented on docker/php/Dockerfile
> +COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer
Думаю, да. Пока чтобы пайплайн отрабатывал на 1 composer'е. Потом будем расширять пайплайны.

2021-01-21 09:26 UTC, andomiell approved these changes

2021-01-22 09:20 UTC, ashimolin approved these changes

2021-01-22 09:59 UTC, merged